origin: bavirtual/moodle-enrol_bycategory

# Grant repository scoped permissions
# NOTE: Every statement will always implicitly grant `metadata: read` permission.
statements:
  - subjects:
      - repo:${origin}:ref:refs/heads/main
      - repo:${origin}:ref:refs/tags/v*
      - repo:bavirtual/moodle-docker:workflow_ref:bavirtual/moodle-docker/.github/workflows/dockerpublish.yml@refs/heads/main

    permissions: # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps
      contents: read
