name: Trigger Moodle Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          permissions: |
            actions: write

      - name: Trigger workflow
        run: >-
          gh workflow
          run bavirtual/moodle-docker/.github/workflows/dockerpublish.yml
          --field logLevel=debug
        env:
          GITHUB_TOKEN: ${{steps.access-token.outputs.token}}
