name: Trigger Moodle Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build-moodle:
    runs-on: ubuntu-latest
    steps:
      - uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          permissions: |
            actions: write

      - name: Trigger workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{steps.access-token.outputs.token}}" \
          https://api.github.com/repos/bavirtual/moodle-docker/dispatches -d \
          '{"event_type": "workflow_dispatch"}'
